[window]
opacity = 0.9
blur = true

[font]
normal = {family="UbuntuMono Nerd Font", style="Regular"}
bold = {family="UbuntuMono Nerd Font", style="Bold"}
italic = {family="UbuntuMono Nerd Font", style="Italic"}
size = 14

[colors.primary]
background = '#282c34'
foreground = '#57c7ff'

# Normal colors
[colors.normal]
black   = '#1e2127'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#abb2bf'

# Bright colors
[colors.bright]
black   = '#5c6370'
red     = '#e06c75'
green   = '#98c379'
yellow  = '#d19a66'
blue    = '#61afef'
magenta = '#c678dd'
cyan    = '#56b6c2'
white   = '#ffffff'
